apiVersion: apps/v1
kind: Deployment
metadata:
  name: product-catalogue
  labels:
    app: product-catalogue
spec:
  replicas: 2
  selector:
    matchLabels:
      app: product-catalogue
  template:
    metadata:
      labels:
        app: product-catalogue
    spec:
      containers:
        - name: product-catalogue
          image: product-catalogue:v1  # or your Docker Hub image if pushed
          ports:
            - containerPort: 5000
          resources:
            limits:
              memory: "128Mi"
              cpu: "500m"
---
apiVersion: v1
kind: Service
metadata:
  name: product-catalogue-service
spec:
  selector:
    app: product-catalogue
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
  type: NodePort
